config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'tweets#index'
  resources :users do
    collection do
      get :following, :followers
    end
  end
  resources :tweets do
    resources :images
  end
  resources :relationships, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord

  mount_uploader :file, FilesUploader

  belongs_to :tweet, optional: true

  validates :file, null: false
end

app/models/relationship.rb
class Relationship < ApplicationRecord

   belongs_to :follower, class_name: "User"
   belongs_to :followed, class_name: "User"
   validates :follower_id, presence: true
   validates :followed_id, presence: true
end

app/models/tweet.rb
class Tweet < ApplicationRecord

  belongs_to :user
  has_many :images
  accepts_nested_attributes_for :images

  validates :user_id, null: false
end

app/models/user.rb
class User < ApplicationRecord


  has_many :tweets
  #フォローしているユーザーをfollower_idという外部キーを使って特定しなくてはなりません。また、followerというクラス名は存在しないので、ここでもRailsに正しいクラス名を伝える必要が発生します。⬇️
  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
  has_many :following, through: :active_relationships, source: :followed #following配列の元はfollowed idの集合である
  has_many :followers, through: :passive_relationships, source: :follower

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, null: false
  validates :user_identifier, null: false
  mount_uploader :image, ImageUploader
  mount_uploader :header_image, HeaderUploader
    # ユーザーをフォローする
   def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

   # ユーザーをフォロー解除する
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # 現在のユーザーがother_userをフォローしてたらtrueを返す
  def following?(other_user)
    following.include?(other_user)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!
  before_action :set_tweet
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_out_path_for(resource)
    new_user_session_path
  end

  def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :user_identifier, :image])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name, :image, :header_image])
  end

  def set_tweet
    @tweet = Tweet.new
    @tweet.images.build
  end

end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def create
    user = User.find(params[:followed_id])
    current_user.follow(user)
    redirect_to root_path
  end

  def destroy
    user = Relationship.find(params[:id]).followed
    current_user.unfollow(user)
    redirect_to root_path
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    timeLine_user_ids = current_user.following.ids << current_user.id
    @tweets = Tweet.where(user_id: timeLine_user_ids).order('created_at DESC')
    @users = User.where.not(id: current_user.following.ids)
  end

  def create
    @tweet = current_user.tweets.new(tweet_params)
    if @tweet.save
      redirect_to root_path
    else
      render "index"
    end
  end

  private
  def tweet_params
    params.require(:tweet).permit(:content, images_attributes: [:file])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_unfollowings
  before_action :set_user,  only: [:following, :followers]

  def show
    @user = User.find(params[:id])
    @tweets = @user.tweets.order('created_at DESC')
  end

  def following
    @followings = User.where(id: @user.following.ids)
  end

  def followers
    @followers = User.where(id: @user.followers.ids)
  end

  def set_user
    @user = User.find(params[:format])
  end

  def set_unfollowings
    @users = User.where.not(id: current_user.following.ids)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/header/_header.html.erb
<div class="post-modal-wrapper" id="post-modal">
  <%= render partial: "header/post_modal" %>
</div>
<div class="message-modal-wrapper" id="message-modal">
  <%= render partial: "header/message_modal" %>
</div>

<div class="header">
  <div class="flex_1"></div>
  <ul class="left-menus">
    <li>
      <%= link_to "ホーム", root_path, class: "fa fa-home" %>
    </li>
    <li>
      <a class="fa fa-bolt" href=""> モーメント</a>
    </li>
    <li>
      <a class="fa fa-bell-o" href=""> 通知</a>
    </li>
    <li>
      <a class="fa fa-envelope-o" id="display-message-modal"> メッセージ</a>
    </li>
  </ul>
  <ul class="right-menus">
    <li class="search-query">
      <input type="search" name="" placeholder=" キーワード検索" id="search-query">
      <span>
        <button type="submit" class="fa fa-search"></button>
      </span>
    </li>
    <li class="user_icon">
      <a style="background-image:url(<%= current_user.image.header_icon.to_s %>)"></a>
    </li>
    <li class="tweet_button">
      <p id="display-post-modal">ツイート</p>
    </li>
  </ul>
  <ul class="reload-icon">
    <a href="javascript:location.reload();" class="fa fa-twitter fa-2x"></a>
  </ul>
  <div class="flex_5"></div>
</div>


<div class="header_for_smart_phone">
  <ul class="menus">
    <li>
      <%= link_to "", root_path, class: "fa fa-home" %>
    </li>
    <li>
      <a class="fa fa-bolt" href=""></a>
    </li>
    <li>
      <a class="fa fa-bell-o" href=""></a>
    </li>
    <li>
      <a class="fa fa-envelope-o" id="display-message-modal"></a>
    </li>
    <li class="tweet_button">
      <p id="display-post-modal" class="fa fa-paper-plane"></p>
    </li>
  </ul>
</div>

app/views/header/_message_modal.html.erb
<div class="colse-modal-area"></div>
<div class="modal">
  <div id="login-form">
    <h2>メッセージ</h2>
    <form action="#">
      <div>
        <textarea name="" class="form-control" type="text" placeholder="今どうしてる？"></textarea>
      </div>
      <div>
        <input type="submit" value="ツイート" id="submit-btn">
      </div>
    </form>
  </div>
</div>

app/views/header/_post_modal.html.erb
<div class="colse-modal-area">
</div>
<div class="modal">
  <%= form_for @tweet do |f| %>
    <h2>ツイートする</h2>
    <div class="form_area">
      <div class="textarea">
        <%= f.text_area :content, autofocus: true, placeholder: "いまどうしてる？", class: "form-control" %>
      </div>
      <div class="images_preview_area">
      </div>
      <div class="post_modal_footer">
          <div class="icons", id="append_file_field">
            <%= f.fields_for :images do |i| %>
              <label class="label-item" id="label_0">
                <i class="fa fa-image"></i>
                <%= i.file_field :file, name: "tweet[images_attributes][0][file]",class: "file_field", style: "display:none;" %>
              </label>
            <% end %>
          </div>
          <i class="fa fa-money icons"></i>
          <i class="fa fa-tasks icons"></i>
          <i class="fa fa-map-marker icons"></i>
          <%= f.submit :ツイート, class: "submit-btn" %>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SNS</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>

app/views/tweets/index.html.erb
<%= render partial: "header/header" %>
<div class="content">
  <div class="hole-content">
    <div class="flex">
    </div>
    <div class="left-content">
      <div class="account-info">
        <%= render partial: "tweets/layouts/account_info" %>
      </div>
      <!-- <div class="recommended-trend">
        <%= render partial: "tweets/layouts/recommended-trend" %>
      </div> -->
    </div>
    <div class="main-content">
      <div class="tweet-wrapper">
        <%= render partial: "tweets/layouts/post_area" %>
      </div>
      <div class="notificaiton-wrapper">
      </div>
      <div class="tweets-wrapper">
        <ol>
          <%= render partial: "tweets/layouts/tweets_item" %>
        </ol>
      </div>
    </div>
    <div class="right-content">
      <div class="recommended_users">
        <%= render partial: "tweets/layouts/recommended_users" %>
      </div>
      <!-- <div class="advertisements">
      </div> -->
    </div>
    <div class="flex">
    </div>
  </div>
</div>

app/views/tweets/layouts/_account_info.html.erb
<div class="account-info">
  <div class="header-image" style="background-image:url(<%= current_user.header_image.home.to_s %>">
  </div>
  <div class="account-idenfication">
    <label><a href="/users/<%= current_user.id %>">
      <p class="account-icon" style="background-image:url(<%= current_user.image.account_info.to_s %>"></p>
    </a></label>
    <div class="account-name-id">
      <div>
        <a href="/users/<%= current_user.id %>">
          <span><%= current_user.name %></span>
        </a>
      </div>
      <a href="/users/<%= current_user.id %>">
        <em>@<%= current_user.user_identifier %></em>
      </a>
    </div>
  </div>
  <div class="account-incidental">
    <div class="incidential-list">
      <div class="tweets">
        <a href="/users/<%= current_user.id %>">
          <span class="statusLabel">ツイート</span>
          <span class="statusValue"><%= current_user.tweets.count %></span>
        </a>
      </div>
      <div class="follow_user">
        <label><a href="<%= following_users_path(current_user) %>">
          <span class="statusLabel">フォロー</span>
          <span class="statusValue"><%= current_user.following.count %></span>
        </a></label>
      </div>
      <div class="followed_user">
        <a href="<%= followers_users_path(current_user) %>">
          <span class="statusLabel">フォロワー</span>
          <span class="statusValue"><%= current_user.followers.count %></span>
        </a>
      </div>
    </div>
  </div>
</div>

app/views/tweets/layouts/_post_area.html.erb
<div class="post_area">
  <%= form_for @tweet do |f| %>
    <ul>
      <li class="user_icon_area">
        <div class="user-icon" style="background-image:url(<%= current_user.image.post_area.to_s %>">
        </div>
      </li>
      <li id="post-input-fadeOut">
        <%= f.text_field :content, placeholder: "いまどうしてる？" %>
        <label>
          <input type="file" style="display:none;">
          <span class="fa fa-image"></span>
        </label>
      </li>
      <li style="display:none;" id="post-textarea">
        <div class="main_textarea_area">
          <%= f.text_area :content, autofocus: true, placeholder: "いまどうしてる？" %>
          <div id="post-textarea-footer">
            <label>
              <input type="file" name="" style="display:none;">
              <i class="fa fa-image"></i>
            </label>
            <i class="fa fa-money"></i>
            <i class="fa fa-tasks"></i>
            <i class="fa fa-map-marker"></i>
            <%= f.button :ツイート, type: "submit", class: "post-submit-btn" %>
          </div>
        </div>
      </li>
    </ul>
  <% end %>
</div>

app/views/tweets/layouts/_recommended-trend.html.erb
<div class="recommended-trend-area">
  <div class="">
    <h2>おすすめトレンド</h2>
  </div>
</div>

app/views/tweets/layouts/_recommended_user_item.html.erb
<% @users.each do |user| %>
  <% unless user == current_user %>
    <div class="user_list_item">
      <a href="/users/<%= user.id %>">
        <div class="user_icon" style="background-image:url(<%= user.image.recommended_users.to_s %>"></div>
      </a>
      <div class="user_info_and_follow_req">
        <label><a href="/users/<%= user.id %>"><span id="user_name"><%= user.name %></span>・<span id="user_identifier">@<%= user.user_identifier %></span></a></label>
        <% if current_user.following?(user) %>
            <%= form_for(current_user.active_relationships.find_by(followed_id: user.id),html: { method: :delete }) do |f| %>
              <%= f.submit "フォロー中", class: "btn" %>
            <% end %>
        <% else %>
          <%= form_for(current_user.active_relationships.build) do |f| %>
            <div><%= hidden_field_tag :followed_id, user.id %></div>
            <%= f.submit "フォローする", class: "btn follow" %>
          <% end %>
        <% end %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/tweets/layouts/_recommended_users.html.erb
<div  class="users_list">
  <div class="user_list_titile">
    <h3>おすすめユーザー</h3>
  </div>
  <div class="user_list_items">
    <%= render partial: "tweets/layouts/recommended_user_item" %>
  </div>
</div>
<div class="recommendation_message">
  <p class="fa fa-user-plus"> 知り合いを見つけましょう</p>
</div>

app/views/tweets/layouts/_tweets_item.html.erb
<% @tweets.each do |tweet| %>
  <li class="one-tweet-content">
    <div class="user-account-info">
      <div class="icon-image" style="background-image:url(<%= tweet.user.image.tweet_item.to_s %>)">
      </div>
    </div>
    <div class="tweet-content">
      <div class="tweet-header">
        <a href="/users/<%= tweet.user.id %>">
          <span class="tweet-header_user-name"><%= tweet.user.name %></span>
          <span class="tweet-header_user-id">@<%= tweet.user.user_identifier %></span>
        </a>
        <small>・</small>
        <small class="tweetTime"><%= tweet.created_at.strftime("%Y-%m-%d %H:%M") %></small>
        <em class="fa fa-angle-down"></em>
      </div>
      <div class="tweet-text">
        <%= simple_format(tweet.content) %>
        <% tweet.images.each do |image| %>
          <img src="<%= image.file.sample.to_s %>">
        <% end %>
      </div>
      <div class="tweet-footer">
        <span class="fa fa-comment-o"></span>
        <span class="fa fa-retweet"></span>
        <span class="fa fa-heart-o"></span>
        <span class="fa fa-envelope-o"></span>
      </div>
    </div>
  </li>
<% end %>

app/views/users/_tweet_item.html.erb
<% @user.tweets.each do |t| %>
<li class="one-tweet-content">
  <div class="user-account-info">
    <div class="icon-image" style="background-image:url(<%= t.user.image.tweet_item.to_s %>)">
    </div>
  </div>
  <div class="tweet-content">
    <div class="tweet-header">
      <span class="tweet-header_user-name"><%= @user.name %></span>
      <span class="tweet-header_user-id">@<%= @user.user_identifier %></span>
      <small>・</small>
      <small class="tweetTime"><%= t.created_at.strftime("%Y-%m-%d %H:%M") %></small>
      <em class="fa fa-angle-down"></em>
    </div>
    <div class="tweet-text">
      <%= simple_format(t.content) %>
    </div>
    <div class="tweet-footer">
      <span class="fa fa-comment-o"></span>
      <span class="fa fa-retweet"></span>
      <span class="fa fa-heart-o"></span>
      <span class="fa fa-envelope-o"></span>
    </div>
  </div>
</li>
<% end %>

app/views/users/followers.html.erb
<%= render partial: "header/header" %>
<%= render partial: "users/layouts/common_template" %>
<div class="main_content">
  <div class="margin"></div>
  <div class="left_info">
    <h3><%= @user.name %></h3>
    <h4> @<%= @user.user_identifier %></h4>
    <% if current_user==@user %>
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn' %>
    <% end %>
  </div>
  <div class="user_content">
    <%= render partial: "users/layouts/follower_user_item" %>
  </div>
  <div class="margin"></div>
</div>

app/views/users/following.html.erb
<%= render partial: "header/header" %>
<%= render partial: "users/layouts/common_template" %>
<div class="main_content">
  <div class="margin"></div>
  <div class="left_info">
    <h3><%= @user.name %></h3>
    <h4> @<%= @user.user_identifier %></h4>
    <% if current_user==@user %>
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn' %>
    <% end %>
  </div>
  <div class="user_content">
    <%= render partial: "users/layouts/following_user_item" %>
  </div>
  <div class="margin"></div>
</div>

app/views/users/layouts/_common_template.html.erb
<div class="user_template">
  <div class="header_image" style="background-image:url(<%= @user.header_image.users_controller_template.to_s %>">
  </div>
  <div class="icon_and_status">
    <ul>
      <li class="icon" style="background-image:url(<%= @user.image.users_show.to_s %>"></li>
      <li>
        <ul>
          <li><label><a href="/users/<%= @user.id %>">
            <div>ツイート</div>
            <div class="length"><%= @user.tweets.count %></div></a></label>
          </li>
          <li><label><a href="<%= following_users_path(@user) %>">
            <div>フォロー</div>
            <div class="length"><%= @user.following.count %></div></a></label>
          </li>
          <li><label><a href="<%= followers_users_path(@user) %>">
            <div>
              フォロワー
            </div>
            <div class="length">
              <%= @user.followers.count %>
            </div></a></label>
          </li>
        </ul>
      </li>
      <li class="follow_req">
        <% if current_user==@user %>
          <%= link_to "プロフィール編集", edit_user_registration_path, class: 'btn' %>
        <% else %>
          <% if current_user.following?(@user) %>
            <%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),html: { method: :delete }) do |f| %>
              <%= f.submit "フォロー中", class: "btn" %>
            <% end %>
          <% else %>
            <%= form_for(current_user.active_relationships.build) do |f| %>
              <div><%= hidden_field_tag :followed_id, @user.id %></div>
              <%= f.submit "フォローする", class: "btn follow" %>
            <% end %>
          <% end %>
        <% end %>
      </li>
    </ul>
  </div>
</div>

app/views/users/layouts/_follower_user_item.html.erb
<% @followers.each do |user| %>
  <div class="user_item">
    <div class="user_header">
    </div>
    <div class="user_info">
      <a href="/users/<%= user.id %>">
        <div class="user_icon" style="background-image:url(<%= user.image.account_info.to_s %>)" ></div>
      </a>
      <div class="follow_request">
         <% if current_user.following?(user) %>
            <%= form_for(current_user.active_relationships.find_by(followed_id: user.id),html: { method: :delete }) do |f| %>
              <%= f.submit "フォロー中", class: "btn" %>
            <% end %>
        <% else %>
          <%= form_for(current_user.active_relationships.build) do |f| %>
            <div><%= hidden_field_tag :followed_id, user.id %></div>
            <%= f.submit "フォローする", class: "btn follow" %>
          <% end %>
        <% end %>
      </div>
      <div class="user_status">
        <div class="user_name">
          <label><a href="/users/<%= user.id %>">
          <%= user.name %></a></label>
        </div>
        <div class="user_identifier">
          <label><a href="/users/<%= user.id %>">
          @<%= user.user_identifier %></a></label>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/users/layouts/_following_user_item.html.erb
<% @followings.each do |user| %>
  <div class="user_item">
    <div class="user_header" style="background-image:url(<%= user.header_image.relationships.to_s %>)">
    </div>
    <div class="user_info">
      <a href="/users/<%= user.id %>">
        <div class="user_icon" style="background-image:url(<%= user.image.account_info.to_s %>)" ></div>
      </a>
      <div class="follow_request">
         <% if current_user.following?(user) %>
            <%= form_for(current_user.active_relationships.find_by(followed_id: user.id),html: { method: :delete }) do |f| %>
              <%= f.submit "フォロー中", class: "btn" %>
            <% end %>
        <% else %>
          <%= form_for(current_user.active_relationships.build) do |f| %>
            <div><%= hidden_field_tag :followed_id, user.id %></div>
            <%= f.submit "フォローする", class: "btn follow" %>
          <% end %>
        <% end %>
      </div>
      <div class="user_status">
        <div class="user_name">
          <a href="/users/<%= user.id %>">
            <%= user.name %>
          </a>
        </div>
        <div class="user_identifier">
          <a href="/users/<%= user.id %>">
            @<%= user.user_identifier %>
          </a>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/users/layouts/_tweet_item.html.erb
<% @tweets.each do |t| %>
  <li class="one-tweet-content">
    <div class="user-account-info">
      <div class="icon-image" style="background-image:url(<%= t.user.image.tweet_item.to_s %>)">
      </div>
    </div>
    <div class="tweet-content">
      <div class="tweet-header">
        <span class="tweet-header_user-name"><%= @user.name %></span>
        <span class="tweet-header_user-id">@<%= @user.user_identifier %></span>
        <small>・</small>
        <small class="tweetTime"><%= t.created_at.strftime("%Y-%m-%d %H:%M") %></small>
        <em class="fa fa-angle-down"></em>
      </div>
      <div class="tweet-text">
        <%= simple_format(t.content) %>
        <% t.images.each do |image| %>
            <img src="<%= image.file.sample.to_s %>">
        <% end %>
      </div>
      <div class="tweet-footer">
        <span class="fa fa-comment-o"></span>
        <span class="fa fa-retweet"></span>
        <span class="fa fa-heart-o"></span>
        <span class="fa fa-envelope-o"></span>
      </div>
    </div>
  </li>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <h3>：アカウントをすでにお持ちの方</h3>
  <%= link_to "　　ログイン", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <h3>：アカウントをお持ちでない方</h3>
  <%= link_to "アカウント作成", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <h3>：パスワードをお忘れの方</h3>
  <%= link_to "パスワード再設定", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<%= render partial: "header/header" %>
<%= render partial: "users/layouts/common_template" %>
<div class="main_content">
  <div class="margin"></div>
  <div class="left_info">
    <h3><%= @user.name %></h3>
    <h4> @<%= @user.user_identifier %></h4>
    <% if current_user==@user %>
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn' %>
    <% end %>
  </div>
  <div class="tweets-wrapper">
    <ol>
      <% if @tweets.count != 0 %>
        <%= render partial: "users/layouts/tweet_item" %>
      <% else %>
        <li>まだツイートがありません</li>
      <% end %>
    </ol>
  </div>
  <div class="right_bar">
    <div class="recommended_users">
      <%= render partial: "tweets/layouts/recommended_users" %>
    </div>
  </div>
  <div class="margin"></div>
</div>